server:
  port: 8090
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.127.131:3306/qbp
    username: qbp
    password: qbp
#    url: jdbc:mysql://localhost:3306/qbp
#    username: root
#    password: 252748377

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml文件位置
  type-aliases-package: com.questionbrushingplatform.pojo.entity #别名扫描包
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
  global-config:
    db-config:
      id-type: auto #主键策略，自增
      update-strategy: not_null #更新策略，只更新非空字段
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值

qbp:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: qbp666
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication